// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: raft.proto

package repl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryType int32

const (
	EntryType_ENTRY_NORMAL      EntryType = 0
	EntryType_ENTRY_CONF_CHANGE EntryType = 1
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_NORMAL",
		1: "ENTRY_CONF_CHANGE",
	}
	EntryType_value = map[string]int32{
		"ENTRY_NORMAL":      0,
		"ENTRY_CONF_CHANGE": 1,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_MSG_UNKNOWN        MessageType = 0
	MessageType_MSG_APP            MessageType = 1
	MessageType_MSG_APP_RESP       MessageType = 2
	MessageType_MSG_VOTE           MessageType = 3
	MessageType_MSG_VOTE_RESP      MessageType = 4
	MessageType_MSG_SNAP           MessageType = 5
	MessageType_MSG_HEARTBEAT      MessageType = 6
	MessageType_MSG_HEARTBEAT_RESP MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MSG_UNKNOWN",
		1: "MSG_APP",
		2: "MSG_APP_RESP",
		3: "MSG_VOTE",
		4: "MSG_VOTE_RESP",
		5: "MSG_SNAP",
		6: "MSG_HEARTBEAT",
		7: "MSG_HEARTBEAT_RESP",
	}
	MessageType_value = map[string]int32{
		"MSG_UNKNOWN":        0,
		"MSG_APP":            1,
		"MSG_APP_RESP":       2,
		"MSG_VOTE":           3,
		"MSG_VOTE_RESP":      4,
		"MSG_SNAP":           5,
		"MSG_HEARTBEAT":      6,
		"MSG_HEARTBEAT_RESP": 7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          *uint64                `protobuf:"varint,2,opt,name=Term,proto3,oneof" json:"Term,omitempty"`
	Index         *uint64                `protobuf:"varint,3,opt,name=Index,proto3,oneof" json:"Index,omitempty"`
	Type          *EntryType             `protobuf:"varint,1,opt,name=Type,proto3,enum=raft.EntryType,oneof" json:"Type,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=Data,proto3,oneof" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetTerm() uint64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *Entry) GetIndex() uint64 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *Entry) GetType() EntryType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return EntryType_ENTRY_NORMAL
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=raft.MessageType" json:"type,omitempty"`
	To            int64                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	From          int64                  `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Vote          *RequestVote           `protobuf:"bytes,4,opt,name=vote,proto3" json:"vote,omitempty"`
	VoteResp      *RequestVoteResponse   `protobuf:"bytes,5,opt,name=voteResp,proto3" json:"voteResp,omitempty"`
	Entries       *AppendEntries         `protobuf:"bytes,6,opt,name=entries,proto3" json:"entries,omitempty"`
	EntriesResp   *AppendEntriesResponse `protobuf:"bytes,7,opt,name=entriesResp,proto3" json:"entriesResp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_UNKNOWN
}

func (x *Message) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Message) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Message) GetVote() *RequestVote {
	if x != nil {
		return x.Vote
	}
	return nil
}

func (x *Message) GetVoteResp() *RequestVoteResponse {
	if x != nil {
		return x.VoteResp
	}
	return nil
}

func (x *Message) GetEntries() *AppendEntries {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Message) GetEntriesResp() *AppendEntriesResponse {
	if x != nil {
		return x.EntriesResp
	}
	return nil
}

type RequestVote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          *uint64                `protobuf:"varint,1,opt,name=term,proto3,oneof" json:"term,omitempty"`
	CandidateId   int64                  `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVote) Reset() {
	*x = RequestVote{}
	mi := &file_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVote) ProtoMessage() {}

func (x *RequestVote) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVote.ProtoReflect.Descriptor instead.
func (*RequestVote) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2}
}

func (x *RequestVote) GetTerm() uint64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *RequestVote) GetCandidateId() int64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVote) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVote) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type AppendEntries struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Term        int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId    int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIdx  int64                  `protobuf:"varint,3,opt,name=prev_log_idx,json=prevLogIdx,proto3" json:"prev_log_idx,omitempty"`
	PrevLogTerm int64                  `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	// empty for heartbeat messages from leader to followers
	Entries         []*Log `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommitIdx int64  `protobuf:"varint,6,opt,name=leader_commit_idx,json=leaderCommitIdx,proto3" json:"leader_commit_idx,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppendEntries) Reset() {
	*x = AppendEntries{}
	mi := &file_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntries) ProtoMessage() {}

func (x *AppendEntries) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntries.ProtoReflect.Descriptor instead.
func (*AppendEntries) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{4}
}

func (x *AppendEntries) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntries) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntries) GetPrevLogIdx() int64 {
	if x != nil {
		return x.PrevLogIdx
	}
	return 0
}

func (x *AppendEntries) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntries) GetEntries() []*Log {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntries) GetLeaderCommitIdx() int64 {
	if x != nil {
		return x.LeaderCommitIdx
	}
	return 0
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          *Cmd                   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{5}
}

func (x *Log) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Log) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Log) GetData() *Cmd {
	if x != nil {
		return x.Data
	}
	return nil
}

type Cmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	RequestId     uint64                 `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cmd) Reset() {
	*x = Cmd{}
	mi := &file_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cmd) ProtoMessage() {}

func (x *Cmd) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cmd.ProtoReflect.Descriptor instead.
func (*Cmd) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{6}
}

func (x *Cmd) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Cmd) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Cmd) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Cmd) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentTerm   int64                  `protobuf:"varint,1,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{7}
}

func (x *AppendEntriesResponse) GetCurrentTerm() int64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_raft_proto protoreflect.FileDescriptor

const file_raft_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"raft.proto\x12\x04raft\"\xa3\x01\n" +
	"\x05Entry\x12\x17\n" +
	"\x04Term\x18\x02 \x01(\x04H\x00R\x04Term\x88\x01\x01\x12\x19\n" +
	"\x05Index\x18\x03 \x01(\x04H\x01R\x05Index\x88\x01\x01\x12(\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x0f.raft.EntryTypeH\x02R\x04Type\x88\x01\x01\x12\x17\n" +
	"\x04Data\x18\x04 \x01(\fH\x03R\x04Data\x88\x01\x01B\a\n" +
	"\x05_TermB\b\n" +
	"\x06_IndexB\a\n" +
	"\x05_TypeB\a\n" +
	"\x05_Data\"\xa0\x02\n" +
	"\aMessage\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.raft.MessageTypeR\x04type\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x03R\x02to\x12\x12\n" +
	"\x04from\x18\x03 \x01(\x03R\x04from\x12%\n" +
	"\x04vote\x18\x04 \x01(\v2\x11.raft.RequestVoteR\x04vote\x125\n" +
	"\bvoteResp\x18\x05 \x01(\v2\x19.raft.RequestVoteResponseR\bvoteResp\x12-\n" +
	"\aentries\x18\x06 \x01(\v2\x13.raft.AppendEntriesR\aentries\x12=\n" +
	"\ventriesResp\x18\a \x01(\v2\x1b.raft.AppendEntriesResponseR\ventriesResp\"\x9c\x01\n" +
	"\vRequestVote\x12\x17\n" +
	"\x04term\x18\x01 \x01(\x04H\x00R\x04term\x88\x01\x01\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x03R\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x03R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x03R\vlastLogTermB\a\n" +
	"\x05_term\"L\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\xd7\x01\n" +
	"\rAppendEntries\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\x12 \n" +
	"\fprev_log_idx\x18\x03 \x01(\x03R\n" +
	"prevLogIdx\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x03R\vprevLogTerm\x12#\n" +
	"\aentries\x18\x05 \x03(\v2\t.raft.LogR\aentries\x12*\n" +
	"\x11leader_commit_idx\x18\x06 \x01(\x03R\x0fleaderCommitIdx\"H\n" +
	"\x03Log\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x1d\n" +
	"\x04data\x18\x03 \x01(\v2\t.raft.CmdR\x04data\"\\\n" +
	"\x03Cmd\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x04R\trequestId\"T\n" +
	"\x15AppendEntriesResponse\x12!\n" +
	"\fcurrent_term\x18\x01 \x01(\x03R\vcurrentTerm\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess*4\n" +
	"\tEntryType\x12\x10\n" +
	"\fENTRY_NORMAL\x10\x00\x12\x15\n" +
	"\x11ENTRY_CONF_CHANGE\x10\x01*\x97\x01\n" +
	"\vMessageType\x12\x0f\n" +
	"\vMSG_UNKNOWN\x10\x00\x12\v\n" +
	"\aMSG_APP\x10\x01\x12\x10\n" +
	"\fMSG_APP_RESP\x10\x02\x12\f\n" +
	"\bMSG_VOTE\x10\x03\x12\x11\n" +
	"\rMSG_VOTE_RESP\x10\x04\x12\f\n" +
	"\bMSG_SNAP\x10\x05\x12\x11\n" +
	"\rMSG_HEARTBEAT\x10\x06\x12\x16\n" +
	"\x12MSG_HEARTBEAT_RESP\x10\a28\n" +
	"\vRaftService\x12)\n" +
	"\aProcess\x12\r.raft.Message\x1a\r.raft.Message\"\x00B\fZ\n" +
	"proto/replb\x06proto3"

var (
	file_raft_proto_rawDescOnce sync.Once
	file_raft_proto_rawDescData []byte
)

func file_raft_proto_rawDescGZIP() []byte {
	file_raft_proto_rawDescOnce.Do(func() {
		file_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)))
	})
	return file_raft_proto_rawDescData
}

var file_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_raft_proto_goTypes = []any{
	(EntryType)(0),                // 0: raft.EntryType
	(MessageType)(0),              // 1: raft.MessageType
	(*Entry)(nil),                 // 2: raft.Entry
	(*Message)(nil),               // 3: raft.Message
	(*RequestVote)(nil),           // 4: raft.RequestVote
	(*RequestVoteResponse)(nil),   // 5: raft.RequestVoteResponse
	(*AppendEntries)(nil),         // 6: raft.AppendEntries
	(*Log)(nil),                   // 7: raft.Log
	(*Cmd)(nil),                   // 8: raft.Cmd
	(*AppendEntriesResponse)(nil), // 9: raft.AppendEntriesResponse
}
var file_raft_proto_depIdxs = []int32{
	0, // 0: raft.Entry.Type:type_name -> raft.EntryType
	1, // 1: raft.Message.type:type_name -> raft.MessageType
	4, // 2: raft.Message.vote:type_name -> raft.RequestVote
	5, // 3: raft.Message.voteResp:type_name -> raft.RequestVoteResponse
	6, // 4: raft.Message.entries:type_name -> raft.AppendEntries
	9, // 5: raft.Message.entriesResp:type_name -> raft.AppendEntriesResponse
	7, // 6: raft.AppendEntries.entries:type_name -> raft.Log
	8, // 7: raft.Log.data:type_name -> raft.Cmd
	3, // 8: raft.RaftService.Process:input_type -> raft.Message
	3, // 9: raft.RaftService.Process:output_type -> raft.Message
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_raft_proto_init() }
func file_raft_proto_init() {
	if File_raft_proto != nil {
		return
	}
	file_raft_proto_msgTypes[0].OneofWrappers = []any{}
	file_raft_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_proto_goTypes,
		DependencyIndexes: file_raft_proto_depIdxs,
		EnumInfos:         file_raft_proto_enumTypes,
		MessageInfos:      file_raft_proto_msgTypes,
	}.Build()
	File_raft_proto = out.File
	file_raft_proto_goTypes = nil
	file_raft_proto_depIdxs = nil
}
