// Code generated by MockGen. DO NOT EDIT.
// Source: repl/sm.go

// Package repl is a generated GoMock package.
package repl

import (
	repl "harmonydb/repl/proto/repl"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRaftSM is a mock of RaftSM interface.
type MockRaftSM struct {
	ctrl     *gomock.Controller
	recorder *MockRaftSMMockRecorder
}

// MockRaftSMMockRecorder is the mock recorder for MockRaftSM.
type MockRaftSMMockRecorder struct {
	mock *MockRaftSM
}

// NewMockRaftSM creates a new mock instance.
func NewMockRaftSM(ctrl *gomock.Controller) *MockRaftSM {
	mock := &MockRaftSM{ctrl: ctrl}
	mock.recorder = &MockRaftSMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRaftSM) EXPECT() *MockRaftSMMockRecorder {
	return m.recorder
}

// Advance mocks base method.
func (m *MockRaftSM) Advance() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Advance")
}

// Advance indicates an expected call of Advance.
func (mr *MockRaftSMMockRecorder) Advance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Advance", reflect.TypeOf((*MockRaftSM)(nil).Advance))
}

// Ready mocks base method.
func (m *MockRaftSM) Ready() <-chan Ready {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready")
	ret0, _ := ret[0].(<-chan Ready)
	return ret0
}

// Ready indicates an expected call of Ready.
func (mr *MockRaftSMMockRecorder) Ready() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockRaftSM)(nil).Ready))
}

// Step mocks base method.
func (m_2 *MockRaftSM) Step(m *repl.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Step", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Step indicates an expected call of Step.
func (mr *MockRaftSMMockRecorder) Step(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Step", reflect.TypeOf((*MockRaftSM)(nil).Step), m)
}

// Tick mocks base method.
func (m *MockRaftSM) Tick() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Tick")
}

// Tick indicates an expected call of Tick.
func (mr *MockRaftSMMockRecorder) Tick() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tick", reflect.TypeOf((*MockRaftSM)(nil).Tick))
}
