// Code generated by MockGen. DO NOT EDIT.
// Source: wal/wal.go

// Package repl is a generated GoMock package.
package repl

import (
	repl "harmonydb/repl/proto/repl"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockStorage) Append(log *repl.Log) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Append", log)
}

// Append indicates an expected call of Append.
func (mr *MockStorageMockRecorder) Append(log interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockStorage)(nil).Append), log)
}

// Close mocks base method.
func (m *MockStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorage)(nil).Close))
}

// GetLastLogID mocks base method.
func (m *MockStorage) GetLastLogID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastLogID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetLastLogID indicates an expected call of GetLastLogID.
func (mr *MockStorageMockRecorder) GetLastLogID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastLogID", reflect.TypeOf((*MockStorage)(nil).GetLastLogID))
}

// GetLastLogTerm mocks base method.
func (m *MockStorage) GetLastLogTerm() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastLogTerm")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetLastLogTerm indicates an expected call of GetLastLogTerm.
func (mr *MockStorageMockRecorder) GetLastLogTerm() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastLogTerm", reflect.TypeOf((*MockStorage)(nil).GetLastLogTerm))
}

// GetLog mocks base method.
func (m *MockStorage) GetLog(index int64) *repl.Log {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLog", index)
	ret0, _ := ret[0].(*repl.Log)
	return ret0
}

// GetLog indicates an expected call of GetLog.
func (mr *MockStorageMockRecorder) GetLog(index interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLog", reflect.TypeOf((*MockStorage)(nil).GetLog), index)
}

// GetLogs mocks base method.
func (m *MockStorage) GetLogs() []*repl.Log {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs")
	ret0, _ := ret[0].([]*repl.Log)
	return ret0
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockStorageMockRecorder) GetLogs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockStorage)(nil).GetLogs))
}

// GetLogsAfter mocks base method.
func (m *MockStorage) GetLogsAfter(index int64) []*repl.Log {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogsAfter", index)
	ret0, _ := ret[0].([]*repl.Log)
	return ret0
}

// GetLogsAfter indicates an expected call of GetLogsAfter.
func (mr *MockStorageMockRecorder) GetLogsAfter(index interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogsAfter", reflect.TypeOf((*MockStorage)(nil).GetLogsAfter), index)
}

// NextLogID mocks base method.
func (m *MockStorage) NextLogID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextLogID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// NextLogID indicates an expected call of NextLogID.
func (mr *MockStorageMockRecorder) NextLogID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextLogID", reflect.TypeOf((*MockStorage)(nil).NextLogID))
}

// TruncateAfter mocks base method.
func (m *MockStorage) TruncateAfter(index int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TruncateAfter", index)
}

// TruncateAfter indicates an expected call of TruncateAfter.
func (mr *MockStorageMockRecorder) TruncateAfter(index interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TruncateAfter", reflect.TypeOf((*MockStorage)(nil).TruncateAfter), index)
}
